# Generated by Django 2.0.5 on 2018-11-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_area', '0001_initial'),
        ('food_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_image', models.ImageField(upload_to='images')),
                ('price', models.PositiveIntegerField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_area.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_items.FoodCategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_providers.CooKInfo')),
            ],
            options={
                'verbose_name_plural': 'Food Items',
                'ordering': ['-id'],
            },
        ),
    ]
