# Generated by Django 2.0.5 on 2018-11-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0002_auto_20181121_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_providers.CooKInfo'),
        ),
    ]
