# Generated by Django 2.0.5 on 2018-11-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0002_auto_20181121_2212'),
        ('food_items', '0003_auto_20181121_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='delivery_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.DeliveryPoint'),
            preserve_default=False,
        ),
    ]
