# Generated by Django 2.0.5 on 2018-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0004_fooditems_delivery_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='status',
            field=models.CharField(choices=[('Sold', 'SOLD'), ('Available', 'AVAILABLE')], default='AVAILABLE', max_length=20),
        ),
    ]
