# Generated by Django 2.0.5 on 2018-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0005_auto_20181121_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE'), ('Sold', 'SOLD')], default='AVAILABLE', max_length=20),
        ),
    ]
