# Generated by Django 2.0.5 on 2018-11-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_delivery', '0002_auto_20181121_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.DeliveryPoint')),
            ],
        ),
    ]
