# Generated by Django 2.0.5 on 2018-11-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_providers', '0002_auto_20181121_2137'),
        ('food_area', '0001_initial'),
        ('food_order', '0004_auto_20181122_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_area.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_providers.CooKInfo'),
            preserve_default=False,
        ),
    ]
