# Generated by Django 2.0.5 on 2018-11-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookinfo',
            options={'verbose_name_plural': 'Cook Infos'},
        ),
    ]
